# Generated by Django 5.0.3 on 2024-03-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='address',
        ),
    ]
