# Generated by Django 5.0.3 on 2024-03-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wid',
            field=models.TextField(default=''),
        ),
    ]
