# Generated by Django 5.0.3 on 2024-03-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
