# Generated by Django 5.0.3 on 2024-03-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0003_alter_orders_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ware',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
