# Generated by Django 5.0.3 on 2024-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0003_alter_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ware',
            old_name='descriprion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='ware',
            name='count',
            field=models.CharField(max_length=100),
        ),
    ]
