# Generated by Django 5.0.3 on 2024-03-14 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0004_rename_descriprion_ware_description_alter_ware_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.DecimalField(decimal_places=2, max_digits=8)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzproj.client')),
                ('wid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzproj.ware')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
