# Generated by Django 5.0.3 on 2024-03-14 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0005_orders_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.IntegerField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.IntegerField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dzproj.client'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dzproj.ware'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='id',
            field=models.IntegerField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
