# Generated by Django 5.0.3 on 2024-03-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0005_alter_client_id_alter_orders_id_alter_ware_id'),
        ('dzproj', '0005_alter_orders_uid_alter_orders_wid'),
    ]

    operations = [
    ]
