# Generated by Django 5.0.3 on 2024-03-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0006_merge_20240321_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wid',
            field=models.CharField(max_length=100),
        ),
    ]
