# Generated by Django 5.0.3 on 2024-03-14 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0007_alter_client_id_alter_orders_bill_alter_orders_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='bill',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzproj.client'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzproj.ware'),
        ),
        migrations.AlterField(
            model_name='ware',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
