# Generated by Django 5.0.3 on 2024-03-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0007_alter_orders_uid_alter_orders_wid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wid',
            field=models.TextField(default=''),
        ),
    ]
