# Generated by Django 5.0.3 on 2024-03-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0008_alter_orders_uid_alter_orders_wid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersMem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(default='')),
                ('wid', models.TextField(default='')),
                ('regdate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='warmage',
            field=models.ImageField(default='', height_field=35, storage='media', upload_to='media', width_field=16),
        ),
        migrations.AlterField(
            model_name='orders',
            name='regdate',
            field=models.DateField(),
        ),
    ]
