# Generated by Django 5.0.3 on 2024-03-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0009_alter_orders_uid_alter_orders_wid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uid', to='dzproj.client'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wid', to='dzproj.ware'),
        ),
    ]
