# Generated by Django 5.0.3 on 2024-03-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0009_ordersmem_orders_warmage_alter_orders_regdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='warmage',
        ),
        migrations.AddField(
            model_name='ware',
            name='warmage',
            field=models.ImageField(default='', height_field=35, storage='media', upload_to='media', width_field=16),
        ),
    ]
