# Generated by Django 5.0.3 on 2024-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0011_rename_warmage_ware_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='image',
            field=models.ImageField(blank=True, null=True, storage='media', upload_to='media'),
        ),
    ]
