# Generated by Django 5.0.3 on 2024-03-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0011_alter_client_id_alter_ware_id_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.DecimalField(decimal_places=2, max_digits=8)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
