# Generated by Django 5.0.3 on 2024-03-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0013_orders_uid_orders_wid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
