# Generated by Django 5.0.3 on 2024-03-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzproj', '0014_alter_orders_uid_alter_orders_wid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='uid',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='wid',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
